[package]
name = "octets"
version = "0.3.0"
authors = ["Alessandro Ghedini <alessandro@ghedini.me>"]
edition = "2018"
description = "Zero-copy abstraction for parsing and constructing network packets"
keywords = ["quic", "http3"]
categories = ["network-programming"]
license = "BSD-2-Clause"
publish = { workspace = true }
repository = { workspace = true }